### ISSUE TITLE
 com.google.re2j.PatternSyntaxException: error parsing regexp: invalid or unsupported Perl syntax: `(?!`

### ISSUE THREAD

**Issue by ravipras8** [google/re2j#147]
Hi, because of sonar issue i am migrating my java 1.8 regex to re2j regex 1.6
FYI: i am using it inside my springboot project

the code throwing the error.
Pattern.compile("^(?!.*\"xml\":)(.*)", Pattern.CASE_INSENSITIVE)

here is the stack trace 
 com.google.re2j.PatternSyntaxException: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
	at com.google.re2j.Parser.parsePerlFlags(Parser.java:1139) ~[re2j-1.6.jar:?]
	at com.google.re2j.Parser.parseInternal(Parser.java:811) ~[re2j-1.6.jar:?]
	at com.google.re2j.Parser.parse(Parser.java:788) ~[re2j-1.6.jar:?]
	at com.google.re2j.RE2.compileImpl(RE2.java:187) ~[re2j-1.6.jar:?]
	at com.google.re2j.Pattern.compile(Pattern.java:149) ~[re2j-1.6.jar:?]
	at com.google.re2j.Pattern.compile(Pattern.java:137) ~[re2j-1.6.jar:?]
	at com.ficostudio.framework.config.XSSRequestInterceptor.<clinit>(XSSRequestInterceptor.java:59) ~[classes/:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_291]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_291]
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:591) ~[spring-core-5.3.9.jar:5.3.9]
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363) ~[spring-core-5.3.9.jar:5.3.9]
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:585) ~[spring-core-5.3.9.jar:5.3.9]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110) ~[spring-core-5.3.9.jar:5.3.9]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108) ~[spring-core-5.3.9.jar:5.3.9]
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[spring-core-5.3.9.jar:5.3.9]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_291]
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[spring-core-5.3.9.jar:5.3.9]
	... 20 more

**Comment by sjamesr** [comment]
RE2/J doesn't support this negative lookahead syntax `(?!...)`. For rationale, see https://github.com/google/re2/wiki/WhyRE2 (this is for the RE2 project but the same rationale applies here).

You might not need the safety that RE2/J tries to offer if your inputs are trusted.
