### ISSUE TITLE
Pattern Leading to NullPointerException

### ISSUE THREAD

**Issue by schirrmacher** [google/re2j#148]
When I compile the pattern: `"..|.#|.."`:

`Pattern.compile("..|.#|..")`

I get `java.lang.NullPointerException` exception.

```
== Java Exception: java.lang.NullPointerException: Cannot read the array length because "subMax.runes" is null
	at com.google.re2j.Parser.factor(Parser.java:552)
	at com.google.re2j.Parser.collapse(Parser.java:344)
	at com.google.re2j.Parser.factor(Parser.java:512)
	at com.google.re2j.Parser.collapse(Parser.java:344)
	at com.google.re2j.Parser.alternate(Parser.java:294)
	at com.google.re2j.Parser.parseInternal(Parser.java:975)
	at com.google.re2j.Parser.parse(Parser.java:788)
	at com.google.re2j.RE2.compileImpl(RE2.java:187)
	at com.google.re2j.Pattern.compile(Pattern.java:149)
	at com.google.re2j.Pattern.compile(Pattern.java:107)
```

I applied the Jazzer Fuzzer to your lib. [Maybe an integration is worth it](https://github.com/google/re2j/issues/135).

**Comment by sjamesr** [comment]
This was fixed in #149
