### ISSUE TITLE
Serialization breaks compiled pattern

### ISSUE THREAD

**Issue by av-ast** [google/re2j#24]
Hi,

I'm trying to serialize/deserialize an instance of [com.google.re2j.Pattern](https://github.com/google/re2j/blob/master/java/com/google/re2j/Pattern.java) 
```java
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.re2j.Pattern;
import org.apache.commons.lang3.SerializationUtils;
import org.junit.Test;

import java.util.Map;

public class Re2SerializationTest {
    @Test
    public void test() throws Exception {
        JsonParser parser = new JsonParser();
        JsonObject obj = parser.parse("{\"1\":\"\\\\Atest\\\\z\"}").getAsJsonObject();

        for (Map.Entry<String,JsonElement> t : obj.entrySet()) {
            String rgxp = t.getValue().getAsString();
            System.out.println("rgxp" + " -> " + rgxp);

            // java.util.regex
            java.util.regex.Pattern pattern = java.util.regex.Pattern.compile(rgxp);
            System.out.println(pattern + " -> " + pattern.matcher("test").matches());
            byte[] serializedData = SerializationUtils.serialize(pattern);
            java.util.regex.Pattern pattern2 = SerializationUtils.deserialize(serializedData);
            System.out.println(pattern2 + " -> " + pattern2.matcher("test").matches());

            // com.google.re2j
            Pattern pattern3 = Pattern.compile(rgxp);
            System.out.println(pattern3 + " -> " + pattern3.matches("test"));
            byte[] serializedData2 = SerializationUtils.serialize(pattern3);
            Pattern pattern4 = SerializationUtils.deserialize(serializedData2);
            System.out.println(pattern4 + " -> " + pattern4.matches("test"));
        }
    }
}
```
...and getting the following error:
```
rgxp -> \Atest\z
\Atest\z -> true
\Atest\z -> true
\Atest\z -> true

com.google.re2j.PatternSyntaxException: error parsing regexp: invalid escape sequence: `\A`

	at com.google.re2j.Parser.parseEscape(Parser.java:1439)
	at com.google.re2j.Parser.parseInternal(Parser.java:966)
	at com.google.re2j.Parser.parse(Parser.java:802)
	at com.google.re2j.RE2.compileImpl(RE2.java:183)
	at com.google.re2j.Pattern.readObject(Pattern.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.commons.lang3.SerializationUtils.deserialize(SerializationUtils.java:224)
	at org.apache.commons.lang3.SerializationUtils.deserialize(SerializationUtils.java:268)
	at Re2SerializationTest.test(Re2SerializationTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)


Process finished with exit code 255
```

**Comment by nabhosal** [comment]
Hi, 
I'm facing the same issue, is any one working on this ???

**Comment by av-ast** [comment]
@nabhosal FYI, it's OK in master branch. If it's not already in Maven repo you can just build a JAR from master branch and attach to your project.

**Comment by nabhosal** [comment]
Thanks Alexey. It was really helpful. 
Last release was made a year back, i think its time for a google re2j team to build new release.

**Comment by av-ast** [comment]
@nabhosal glad to help you!

**Comment by sjamesr** [comment]
This should be fixed, please reopen if not.
